// Generate a minimal config.js at build time using environment variables.
// This lets Netlify Git auto-deploys work without committing secrets.
// Required env vars in Netlify: SUPABASE_URL, SUPABASE_ANON_KEY

import { writeFile } from 'node:fs/promises';

const url = process.env.SUPABASE_URL || '';
const key = process.env.SUPABASE_ANON_KEY || '';

if (!/^https?:\/\//i.test(url) || !key) {
  console.error('[generate-config] Missing SUPABASE_URL or SUPABASE_ANON_KEY.');
  console.error('Set them in Netlify → Site settings → Build & deploy → Environment → Environment variables.');
  process.exit(1);
}

const content = `// Auto-generated by tools/generate-config.mjs during Netlify build\nwindow.CONFIG = {\n  supabaseUrl: ${JSON.stringify(url)},\n  supabaseKey: ${JSON.stringify(key)}\n};\nwindow.SUPER_SECRET_CONFIG = window.SUPER_SECRET_CONFIG || window.CONFIG;\n`;

await writeFile(new URL('../config.js', import.meta.url), content, 'utf8');
console.log('[generate-config] Wrote config.js for Supabase.');
